### ISSUE TITLE
Docs on concat and join

### ISSUE THREAD

**Issue by braaannigan** [pola-rs/polars-book#169]
There is no mention of `concat` or `join` in the current book. Propose adding a section to howcani with a first version of this

**Comment by sm-Fifteen** [comment]
Seconded. From the book alone, one would think that `scan_csv` and `read_csv` can only fit multiple files in one dataframe [if all of your captured file match a specific glob pattern](https://github.com/pola-rs/polars-book/blob/03c7041d276d82482650373381a9736be5adfeb7/user_guide/src/multiple_files/intro.md?plain=1#L11-L18), but as I found out in pola-rs/polars#3893, the result (and execution plan in the case of `scan_csv`) is the same as when individually reading each file and then stitching the the resulting frames together.

```py
small_df_list = []

for file_path_str in csv_file_path_list:
	small_df = pl.scan_csv(file_path_str)
	small_df_list.append(small_df)

large_df: pl.LazyFrame = pl.concat(small_df_list)
```

**Comment by zundertj** [comment]
Seems we have both covered now:
- concat: https://pola-rs.github.io/polars-book/user-guide/transformations/concatenation/
- join: https://pola-rs.github.io/polars-book/user-guide/transformations/joins/

**Comment by sm-Fifteen** [comment]
> Seems we have both covered now:
> 
>     * concat: https://pola-rs.github.io/polars-book/user-guide/transformations/concatenation/
> 
>     * join: https://pola-rs.github.io/polars-book/user-guide/transformations/joins/

No mention of them in [IO - Multiple](https://pola-rs.github.io/polars-book/user-guide/io/multiple/), though, which I feel would be beneficial to new users. Otherwise, it seems like the only way of scanning multiple files at once is to figure out a glob pattern to select everything you need at once, but all the globbing does is concatenate the LazyFrames together in the query plan, exactly like concat would.
